version: "3.8"
services:
  carefer-mysql:
    image: mysql:8.0
    container_name: carefer-mysql8-${ENV}
    hostname: carefer-mysql8-${ENV}
    restart: always
    networks:
      - carefer-network
    expose:
      - 3306
    ports:
      - ${CAREFER_MYSQL_HOST_PORT:?err}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${CAREFER_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${CAREFER_MYSQL_DATABASE}
      - MYSQL_USER=${CAREFER_MYSQL_USER}
      - MYSQL_PASSWORD=${CAREFER_MYSQL_PASSWORD}
    volumes:
      - ${CAREFER_MYSQL_HOST_VOLUME}:/var/lib/mysql:delegated
  carefer-php:
    image: carefer-php-${CAREFER_PHP_VERSION}
    build:
      context: ./php-${CAREFER_PHP_VERSION}
    container_name: carefer-php-${ENV}
    hostname: carefer-${ENV}
    working_dir: /var/www
    restart: always
    networks:
      - carefer-network
    expose:
      - 80
    ports:
      - ${CAREFER_HOST_PORT:?err}:80
    environment:
      - PROJECT_PATH=/var/www/public
      - COMPOSER_MEMORY_LIMIT=-1
      - XDEBUG_MODE=${CAREFER_XDEBUG_MODE:-debug}
      - XDEBUG_REMOTE_PORT=${CAREFER_XDEBUG_REMOTE_PORT}
    volumes:
      - ${CAREFER_HOST_WORKING_DIR}:/var/www:delegated
      - ./php-${CAREFER_PHP_VERSION}/.composer:/home/osama/.composer:delegated
      - ./php-${CAREFER_PHP_VERSION}/log/apache2:/var/log/apache2:delegated
    depends_on:
      - carefer-mysql
      - carefer-redis
  carefer-redis:
    image: redis:6.0
    container_name: carefer-redis-${ENV}
    hostname: carefer-redis-${ENV}
    restart: always
    networks:
      - carefer-network
    expose:
      - 6379
    volumes:
      - ${CAREFER_REDIS_HOST_VOLUME:?err}:/data:delegated
  carefer-pma:
    image: phpmyadmin/phpmyadmin
    container_name: carefer-pma-${ENV}
    hostname: carefer-pma-${ENV}
    restart: always
    networks:
      - carefer-network
    expose:
      - 80
    ports:
      - ${CAREFER_PMA_HOST_PORT:?err}:80
    environment:
      - PMA_HOST=carefer-mysql8-${ENV}
      - PMA_PORT=${CAREFER_MYSQL_HOST_PORT}
      - PMA_USER=${CAREFER_MYSQL_USER}
      - PMA_PASSWORD=${CAREFER_MYSQL_PASSWORD}
    depends_on:
      - carefer-mysql

networks:
  carefer-network:
    driver: bridge
